# generated by datamodel-codegen:
#   filename:  customer.json
#   timestamp: 2025-04-08T06:11:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, EmailStr, Field


class Address(BaseModel):
    street: str = Field(..., description="Street address.")
    city: str = Field(..., description="City.")
    state: str = Field(..., description="State.")
    postalCode: str = Field(..., description="Postal code.")
    country: str = Field(..., description="Country.")


class Customer(BaseModel):
    customerId: str = Field(..., description="Unique identifier for the customer.")
    firstName: str = Field(..., description="Customer's first name.")
    lastName: str = Field(..., description="Customer's last name.")
    email: EmailStr = Field(..., description="Customer's email address.")
    phone: Optional[str] = Field(None, description="Customer's phone number.")
    address: Address
