/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A customer's order.
 */
export interface Order {
  /**
   * Unique identifier for the order.
   */
  orderId: string;
  /**
   * The customer who placed the order.
   */
  customerId: string;
  /**
   * The date and time when the order was placed.
   */
  orderDate: string;
  /**
   * Total amount for the order.
   */
  totalAmount: number;
  /**
   * List of items in the order.
   */
  items: {
    /**
     * Product identifier.
     */
    productId: string;
    /**
     * Name of the product.
     */
    productName: string;
    /**
     * Quantity of the product ordered.
     */
    quantity: number;
    /**
     * Price per unit of the product.
     */
    price: number;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
